services:
  nonebot-webui:
    build: .
    image: xisoul/nonebot-webui:latest
    container_name: nonebot-webui
    restart: always
    network_mode: host
    environment:
      - HOST=0.0.0.0
      - PORT=18080
    volumes:
      - ./data:/data
