// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch'
import type {
  AuthTokenV1AuthLoginPostData,
  AuthTokenV1AuthLoginPostError,
  AuthTokenV1AuthLoginPostResponse,
  VerifyTokenV1AuthVerifyPostData,
  VerifyTokenV1AuthVerifyPostError,
  VerifyTokenV1AuthVerifyPostResponse,
  GetAboutVersionV1AboutVersionGetError,
  GetAboutVersionV1AboutVersionGetResponse,
  GetBackupSettingsV1BackupSettingsGetError,
  GetBackupSettingsV1BackupSettingsGetResponse,
  PutBackupSettingsV1BackupSettingsPutData,
  PutBackupSettingsV1BackupSettingsPutError,
  PutBackupSettingsV1BackupSettingsPutResponse,
  PostBackupTestV1BackupTestPostData,
  PostBackupTestV1BackupTestPostError,
  PostBackupTestV1BackupTestPostResponse,
  GetBackupListV1BackupListGetData,
  GetBackupListV1BackupListGetError,
  GetBackupListV1BackupListGetResponse,
  DownloadProjectBackupV1BackupDownloadPostData,
  DownloadProjectBackupV1BackupDownloadPostError,
  DownloadProjectBackupV1BackupDownloadPostResponse,
  UploadProjectBackupV1BackupUploadPostData,
  UploadProjectBackupV1BackupUploadPostError,
  UploadProjectBackupV1BackupUploadPostResponse,
  RestoreRemoteBackupV1BackupRestoreRemotePostData,
  RestoreRemoteBackupV1BackupRestoreRemotePostError,
  RestoreRemoteBackupV1BackupRestoreRemotePostResponse,
  RestoreLocalBackupV1BackupRestoreLocalPostData,
  RestoreLocalBackupV1BackupRestoreLocalPostError,
  RestoreLocalBackupV1BackupRestoreLocalPostResponse,
  RestoreRemoteBackupAsNewV1BackupRestoreAsNewRemotePostData,
  RestoreRemoteBackupAsNewV1BackupRestoreAsNewRemotePostError,
  RestoreRemoteBackupAsNewV1BackupRestoreAsNewRemotePostResponse,
  RestoreLocalBackupAsNewV1BackupRestoreAsNewLocalPostData,
  RestoreLocalBackupAsNewV1BackupRestoreAsNewLocalPostError,
  RestoreLocalBackupAsNewV1BackupRestoreAsNewLocalPostResponse,
  GetFileListV1FileListGetData,
  GetFileListV1FileListGetError,
  GetFileListV1FileListGetResponse,
  CreateFileV1FileCreatePostData,
  CreateFileV1FileCreatePostError,
  CreateFileV1FileCreatePostResponse,
  DeleteFileV1FileDeleteDeleteData,
  DeleteFileV1FileDeleteDeleteError,
  DeleteFileV1FileDeleteDeleteResponse,
  GetFileManagerRootsV1FileManagerRootsGetData,
  GetFileManagerRootsV1FileManagerRootsGetError,
  GetFileManagerRootsV1FileManagerRootsGetResponse,
  GetFileManagerListV1FileManagerListGetData,
  GetFileManagerListV1FileManagerListGetError,
  GetFileManagerListV1FileManagerListGetResponse,
  GetFileManagerContentV1FileManagerContentGetData,
  GetFileManagerContentV1FileManagerContentGetError,
  GetFileManagerContentV1FileManagerContentGetResponse,
  UpdateFileManagerContentV1FileManagerContentPutData,
  UpdateFileManagerContentV1FileManagerContentPutError,
  UpdateFileManagerContentV1FileManagerContentPutResponse,
  CreateFileManagerEntryV1FileManagerCreatePostData,
  CreateFileManagerEntryV1FileManagerCreatePostError,
  CreateFileManagerEntryV1FileManagerCreatePostResponse,
  DeleteFileManagerEntryV1FileManagerDeleteDeleteData,
  DeleteFileManagerEntryV1FileManagerDeleteDeleteError,
  DeleteFileManagerEntryV1FileManagerDeleteDeleteResponse,
  GetGlobalLogSettingsV1LogCenterSettingsGetError,
  GetGlobalLogSettingsV1LogCenterSettingsGetResponse,
  PutGlobalLogSettingsV1LogCenterSettingsPutData,
  PutGlobalLogSettingsV1LogCenterSettingsPutError,
  PutGlobalLogSettingsV1LogCenterSettingsPutResponse,
  GetGlobalLogCatalogV1LogCenterCatalogGetData,
  GetGlobalLogCatalogV1LogCenterCatalogGetError,
  GetGlobalLogCatalogV1LogCenterCatalogGetResponse,
  GetGlobalLogEntriesV1LogCenterEntriesGetData,
  GetGlobalLogEntriesV1LogCenterEntriesGetError,
  GetGlobalLogEntriesV1LogCenterEntriesGetResponse,
  PostGlobalLogEventV1LogCenterEventPostData,
  PostGlobalLogEventV1LogCenterEventPostError,
  PostGlobalLogEventV1LogCenterEventPostResponse,
  InstallNonebotModuleV1StoreNonebotInstallPostData,
  InstallNonebotModuleV1StoreNonebotInstallPostError,
  InstallNonebotModuleV1StoreNonebotInstallPostResponse,
  UninstallNonebotModuleV1StoreNonebotUninstallPostData,
  UninstallNonebotModuleV1StoreNonebotUninstallPostError,
  UninstallNonebotModuleV1StoreNonebotUninstallPostResponse,
  UpdateNonebotPluginV1StoreNonebotUpdatePluginPostData,
  UpdateNonebotPluginV1StoreNonebotUpdatePluginPostError,
  UpdateNonebotPluginV1StoreNonebotUpdatePluginPostResponse,
  GetNonebotStoreItemsV1StoreNonebotListGetData,
  GetNonebotStoreItemsV1StoreNonebotListGetError,
  GetNonebotStoreItemsV1StoreNonebotListGetResponse,
  SearchNonebotStoreItemV1StoreNonebotSearchPostData,
  SearchNonebotStoreItemV1StoreNonebotSearchPostError,
  SearchNonebotStoreItemV1StoreNonebotSearchPostResponse,
  RunProcessV1ProcessRunPostData,
  RunProcessV1ProcessRunPostError,
  RunProcessV1ProcessRunPostResponse,
  StopProcessV1ProcessStopPostData,
  StopProcessV1ProcessStopPostError,
  StopProcessV1ProcessStopPostResponse,
  WriteToProcessV1ProcessWritePostData,
  WriteToProcessV1ProcessWritePostError,
  WriteToProcessV1ProcessWritePostResponse,
  InterruptProcessV1ProcessInterruptPostData,
  InterruptProcessV1ProcessInterruptPostError,
  InterruptProcessV1ProcessInterruptPostResponse,
  OpenTerminalV1ProcessTerminalOpenPostData,
  OpenTerminalV1ProcessTerminalOpenPostError,
  OpenTerminalV1ProcessTerminalOpenPostResponse,
  GetTerminalSessionsV1ProcessTerminalSessionsGetData,
  GetTerminalSessionsV1ProcessTerminalSessionsGetError,
  GetTerminalSessionsV1ProcessTerminalSessionsGetResponse,
  CreateTerminalSessionV1ProcessTerminalSessionCreatePostData,
  CreateTerminalSessionV1ProcessTerminalSessionCreatePostError,
  CreateTerminalSessionV1ProcessTerminalSessionCreatePostResponse,
  SwitchTerminalSessionV1ProcessTerminalSessionSwitchPostData,
  SwitchTerminalSessionV1ProcessTerminalSessionSwitchPostError,
  SwitchTerminalSessionV1ProcessTerminalSessionSwitchPostResponse,
  DeleteTerminalSessionV1ProcessTerminalSessionDeleteDeleteData,
  DeleteTerminalSessionV1ProcessTerminalSessionDeleteDeleteError,
  DeleteTerminalSessionV1ProcessTerminalSessionDeleteDeleteResponse,
  GetTerminalLogKeyV1ProcessTerminalLogKeyGetData,
  GetTerminalLogKeyV1ProcessTerminalLogKeyGetError,
  GetTerminalLogKeyV1ProcessTerminalLogKeyGetResponse,
  ResizeTerminalV1ProcessTerminalResizePostData,
  ResizeTerminalV1ProcessTerminalResizePostError,
  ResizeTerminalV1ProcessTerminalResizePostResponse,
  GetRuntimeLogKeyV1ProcessRuntimeLogKeyGetData,
  GetRuntimeLogKeyV1ProcessRuntimeLogKeyGetError,
  GetRuntimeLogKeyV1ProcessRuntimeLogKeyGetResponse,
  ExecuteCommandV1ProcessExecutePostData,
  ExecuteCommandV1ProcessExecutePostError,
  ExecuteCommandV1ProcessExecutePostResponse,
  GetLogHistoryV1ProcessLogHistoryGetData,
  GetLogHistoryV1ProcessLogHistoryGetError,
  GetLogHistoryV1ProcessLogHistoryGetResponse,
  GetProjectEnvListV1ProjectConfigEnvListGetData,
  GetProjectEnvListV1ProjectConfigEnvListGetError,
  GetProjectEnvListV1ProjectConfigEnvListGetResponse,
  CreateProjectEnvV1ProjectConfigEnvCreatePostData,
  CreateProjectEnvV1ProjectConfigEnvCreatePostError,
  CreateProjectEnvV1ProjectConfigEnvCreatePostResponse,
  DeleteProjectEnvV1ProjectConfigEnvDeleteDeleteData,
  DeleteProjectEnvV1ProjectConfigEnvDeleteDeleteError,
  DeleteProjectEnvV1ProjectConfigEnvDeleteDeleteResponse,
  UseProjectEnvV1ProjectConfigEnvUsePostData,
  UseProjectEnvV1ProjectConfigEnvUsePostError,
  UseProjectEnvV1ProjectConfigEnvUsePostResponse,
  GetProjectMetaConfigV1ProjectConfigMetaDetailGetData,
  GetProjectMetaConfigV1ProjectConfigMetaDetailGetError,
  GetProjectMetaConfigV1ProjectConfigMetaDetailGetResponse,
  GetProjectNonebotConfigV1ProjectConfigNonebotDetailGetData,
  GetProjectNonebotConfigV1ProjectConfigNonebotDetailGetError,
  GetProjectNonebotConfigV1ProjectConfigNonebotDetailGetResponse,
  GetProjectNonebotPluginConfigV1ProjectConfigNonebotPluginDetailGetData,
  GetProjectNonebotPluginConfigV1ProjectConfigNonebotPluginDetailGetError,
  GetProjectNonebotPluginConfigV1ProjectConfigNonebotPluginDetailGetResponse,
  UpdateProjectConfigV1ProjectConfigUpdatePostData,
  UpdateProjectConfigV1ProjectConfigUpdatePostError,
  UpdateProjectConfigV1ProjectConfigUpdatePostResponse,
  GetDotenvFileV1ProjectConfigDotenvGetData,
  GetDotenvFileV1ProjectConfigDotenvGetError,
  GetDotenvFileV1ProjectConfigDotenvGetResponse,
  UpdateDotenvFileV1ProjectConfigDotenvPutData,
  UpdateDotenvFileV1ProjectConfigDotenvPutError,
  UpdateDotenvFileV1ProjectConfigDotenvPutResponse,
  GetPyprojectFileV1ProjectConfigPyprojectGetData,
  GetPyprojectFileV1ProjectConfigPyprojectGetError,
  GetPyprojectFileV1ProjectConfigPyprojectGetResponse,
  UpdatePyprojectFileV1ProjectConfigPyprojectPutData,
  UpdatePyprojectFileV1ProjectConfigPyprojectPutError,
  UpdatePyprojectFileV1ProjectConfigPyprojectPutResponse,
  CreateProjectV1ProjectCreatePostData,
  CreateProjectV1ProjectCreatePostError,
  CreateProjectV1ProjectCreatePostResponse,
  AddProjectV1ProjectAddPostData,
  AddProjectV1ProjectAddPostError,
  AddProjectV1ProjectAddPostResponse,
  GetProjectProfileV1ProjectProfileGetData,
  GetProjectProfileV1ProjectProfileGetError,
  GetProjectProfileV1ProjectProfileGetResponse,
  DeleteProjectV1ProjectDeleteDeleteData,
  DeleteProjectV1ProjectDeleteDeleteError,
  DeleteProjectV1ProjectDeleteDeleteResponse,
  ListProjectV1ProjectListGetError,
  ListProjectV1ProjectListGetResponse,
  CheckProjectTomlV1ProjectCheckTomlPostData,
  CheckProjectTomlV1ProjectCheckTomlPostError,
  CheckProjectTomlV1ProjectCheckTomlPostResponse,
  GetPluginsV1ProjectPluginsGetData,
  GetPluginsV1ProjectPluginsGetError,
  GetPluginsV1ProjectPluginsGetResponse,
  GetAdaptersV1ProjectAdaptersGetData,
  GetAdaptersV1ProjectAdaptersGetError,
  GetAdaptersV1ProjectAdaptersGetResponse,
  GetDriversV1ProjectDriversGetData,
  GetDriversV1ProjectDriversGetError,
  GetDriversV1ProjectDriversGetResponse,
  UpdateProjectAutoStartV1ProjectAutoStartUsePostData,
  UpdateProjectAutoStartV1ProjectAutoStartUsePostError,
  UpdateProjectAutoStartV1ProjectAutoStartUsePostResponse,
  UpdateProjectDirV1ProjectUpdateDirPostData,
  UpdateProjectDirV1ProjectUpdateDirPostError,
  UpdateProjectDirV1ProjectUpdateDirPostResponse,
  GetSecuritySettingsV1SystemSecurityGetError,
  GetSecuritySettingsV1SystemSecurityGetResponse,
  UpdateSecuritySettingsV1SystemSecurityPutData,
  UpdateSecuritySettingsV1SystemSecurityPutError,
  UpdateSecuritySettingsV1SystemSecurityPutResponse,
  GetContainerRuntimeSettingsV1SystemContainerRuntimeGetError,
  GetContainerRuntimeSettingsV1SystemContainerRuntimeGetResponse,
  UpdateContainerRuntimeSettingsV1SystemContainerRuntimePutData,
  UpdateContainerRuntimeSettingsV1SystemContainerRuntimePutError,
  UpdateContainerRuntimeSettingsV1SystemContainerRuntimePutResponse,
  TestRuntimeSettingsConnectivityV1SystemContainerRuntimeTestPostData,
  TestRuntimeSettingsConnectivityV1SystemContainerRuntimeTestPostError,
  TestRuntimeSettingsConnectivityV1SystemContainerRuntimeTestPostResponse,
  BenchmarkRuntimePresetsV1SystemContainerRuntimePresetBenchmarkPostData,
  BenchmarkRuntimePresetsV1SystemContainerRuntimePresetBenchmarkPostError,
  BenchmarkRuntimePresetsV1SystemContainerRuntimePresetBenchmarkPostResponse,
  ListRuntimeProfilesV1SystemContainerRuntimeProfileListGetError,
  ListRuntimeProfilesV1SystemContainerRuntimeProfileListGetResponse,
  SaveRuntimeProfileV1SystemContainerRuntimeProfileSavePostData,
  SaveRuntimeProfileV1SystemContainerRuntimeProfileSavePostError,
  SaveRuntimeProfileV1SystemContainerRuntimeProfileSavePostResponse,
  ApplyRuntimeProfileV1SystemContainerRuntimeProfileApplyPostData,
  ApplyRuntimeProfileV1SystemContainerRuntimeProfileApplyPostError,
  ApplyRuntimeProfileV1SystemContainerRuntimeProfileApplyPostResponse,
  DeleteRuntimeProfileV1SystemContainerRuntimeProfileDeleteDeleteData,
  DeleteRuntimeProfileV1SystemContainerRuntimeProfileDeleteDeleteError,
  DeleteRuntimeProfileV1SystemContainerRuntimeProfileDeleteDeleteResponse
} from './types.gen'

export const client = createClient(createConfig())

export class AuthService {
  /**
   * Auth Token
   * - 登录, 成功后返回 JWT 密钥
   */
  public static authTokenV1AuthLoginPost<ThrowOnError extends boolean = false>(
    options: Options<AuthTokenV1AuthLoginPostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      AuthTokenV1AuthLoginPostResponse,
      AuthTokenV1AuthLoginPostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/auth/login'
    })
  }

  /**
   * Verify Token
   * - 验证 JWT 密钥是否可用, 返回到期时间戳
   */
  public static verifyTokenV1AuthVerifyPost<ThrowOnError extends boolean = false>(
    options: Options<VerifyTokenV1AuthVerifyPostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      VerifyTokenV1AuthVerifyPostResponse,
      VerifyTokenV1AuthVerifyPostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/auth/verify'
    })
  }
}

export class AboutService {
  /**
   * Get About Version
   */
  public static getAboutVersionV1AboutVersionGet<ThrowOnError extends boolean = false>(
    options?: Options<unknown, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      GetAboutVersionV1AboutVersionGetResponse,
      GetAboutVersionV1AboutVersionGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/about/version'
    })
  }
}

export class BackupService {
  /**
   * Get Backup Settings
   */
  public static getBackupSettingsV1BackupSettingsGet<ThrowOnError extends boolean = false>(
    options?: Options<unknown, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      GetBackupSettingsV1BackupSettingsGetResponse,
      GetBackupSettingsV1BackupSettingsGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/backup/settings'
    })
  }

  /**
   * Put Backup Settings
   */
  public static putBackupSettingsV1BackupSettingsPut<ThrowOnError extends boolean = false>(
    options: Options<PutBackupSettingsV1BackupSettingsPutData, ThrowOnError>
  ) {
    return (options?.client ?? client).put<
      PutBackupSettingsV1BackupSettingsPutResponse,
      PutBackupSettingsV1BackupSettingsPutError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/backup/settings'
    })
  }

  /**
   * Post Backup Test
   */
  public static postBackupTestV1BackupTestPost<ThrowOnError extends boolean = false>(
    options: Options<PostBackupTestV1BackupTestPostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      PostBackupTestV1BackupTestPostResponse,
      PostBackupTestV1BackupTestPostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/backup/test'
    })
  }

  /**
   * Get Backup List
   */
  public static getBackupListV1BackupListGet<ThrowOnError extends boolean = false>(
    options: Options<GetBackupListV1BackupListGetData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      GetBackupListV1BackupListGetResponse,
      GetBackupListV1BackupListGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/backup/list'
    })
  }

  /**
   * Download Project Backup
   */
  public static downloadProjectBackupV1BackupDownloadPost<ThrowOnError extends boolean = false>(
    options: Options<DownloadProjectBackupV1BackupDownloadPostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      DownloadProjectBackupV1BackupDownloadPostResponse,
      DownloadProjectBackupV1BackupDownloadPostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/backup/download'
    })
  }

  /**
   * Upload Project Backup
   */
  public static uploadProjectBackupV1BackupUploadPost<ThrowOnError extends boolean = false>(
    options: Options<UploadProjectBackupV1BackupUploadPostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      UploadProjectBackupV1BackupUploadPostResponse,
      UploadProjectBackupV1BackupUploadPostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/backup/upload'
    })
  }

  /**
   * Restore Remote Backup
   */
  public static restoreRemoteBackupV1BackupRestoreRemotePost<ThrowOnError extends boolean = false>(
    options: Options<RestoreRemoteBackupV1BackupRestoreRemotePostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      RestoreRemoteBackupV1BackupRestoreRemotePostResponse,
      RestoreRemoteBackupV1BackupRestoreRemotePostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/backup/restore/remote'
    })
  }

  /**
   * Restore Local Backup
   */
  public static restoreLocalBackupV1BackupRestoreLocalPost<ThrowOnError extends boolean = false>(
    options: Options<RestoreLocalBackupV1BackupRestoreLocalPostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      RestoreLocalBackupV1BackupRestoreLocalPostResponse,
      RestoreLocalBackupV1BackupRestoreLocalPostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/backup/restore/local'
    })
  }

  /**
   * Restore Remote Backup As New
   */
  public static restoreRemoteBackupAsNewV1BackupRestoreAsNewRemotePost<
    ThrowOnError extends boolean = false
  >(options: Options<RestoreRemoteBackupAsNewV1BackupRestoreAsNewRemotePostData, ThrowOnError>) {
    return (options?.client ?? client).post<
      RestoreRemoteBackupAsNewV1BackupRestoreAsNewRemotePostResponse,
      RestoreRemoteBackupAsNewV1BackupRestoreAsNewRemotePostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/backup/restore-as-new/remote'
    })
  }

  /**
   * Restore Local Backup As New
   */
  public static restoreLocalBackupAsNewV1BackupRestoreAsNewLocalPost<
    ThrowOnError extends boolean = false
  >(options?: Options<RestoreLocalBackupAsNewV1BackupRestoreAsNewLocalPostData, ThrowOnError>) {
    return (options?.client ?? client).post<
      RestoreLocalBackupAsNewV1BackupRestoreAsNewLocalPostResponse,
      RestoreLocalBackupAsNewV1BackupRestoreAsNewLocalPostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/backup/restore-as-new/local'
    })
  }
}

export class FileService {
  /**
   * Get File List
   * - 根据提供的路径, 基于 base_dir 返回文件列表
   */
  public static getFileListV1FileListGet<ThrowOnError extends boolean = false>(
    options: Options<GetFileListV1FileListGetData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      GetFileListV1FileListGetResponse,
      GetFileListV1FileListGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/file/list'
    })
  }

  /**
   * Create File
   * - 根据提供的路径, 基于 base_dir 创建文件
   */
  public static createFileV1FileCreatePost<ThrowOnError extends boolean = false>(
    options: Options<CreateFileV1FileCreatePostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      CreateFileV1FileCreatePostResponse,
      CreateFileV1FileCreatePostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/file/create'
    })
  }

  /**
   * Delete File
   * - 根据提供的路径, 基于 base_dir 删除文件
   */
  public static deleteFileV1FileDeleteDelete<ThrowOnError extends boolean = false>(
    options: Options<DeleteFileV1FileDeleteDeleteData, ThrowOnError>
  ) {
    return (options?.client ?? client).delete<
      DeleteFileV1FileDeleteDeleteResponse,
      DeleteFileV1FileDeleteDeleteError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/file/delete'
    })
  }

  /**
   * Get File Manager Roots
   */
  public static getFileManagerRootsV1FileManagerRootsGet<ThrowOnError extends boolean = false>(
    options: Options<GetFileManagerRootsV1FileManagerRootsGetData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      GetFileManagerRootsV1FileManagerRootsGetResponse,
      GetFileManagerRootsV1FileManagerRootsGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/file/manager/roots'
    })
  }

  /**
   * Get File Manager List
   */
  public static getFileManagerListV1FileManagerListGet<ThrowOnError extends boolean = false>(
    options: Options<GetFileManagerListV1FileManagerListGetData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      GetFileManagerListV1FileManagerListGetResponse,
      GetFileManagerListV1FileManagerListGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/file/manager/list'
    })
  }

  /**
   * Get File Manager Content
   */
  public static getFileManagerContentV1FileManagerContentGet<ThrowOnError extends boolean = false>(
    options: Options<GetFileManagerContentV1FileManagerContentGetData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      GetFileManagerContentV1FileManagerContentGetResponse,
      GetFileManagerContentV1FileManagerContentGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/file/manager/content'
    })
  }

  /**
   * Update File Manager Content
   */
  public static updateFileManagerContentV1FileManagerContentPut<
    ThrowOnError extends boolean = false
  >(options: Options<UpdateFileManagerContentV1FileManagerContentPutData, ThrowOnError>) {
    return (options?.client ?? client).put<
      UpdateFileManagerContentV1FileManagerContentPutResponse,
      UpdateFileManagerContentV1FileManagerContentPutError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/file/manager/content'
    })
  }

  /**
   * Create File Manager Entry
   */
  public static createFileManagerEntryV1FileManagerCreatePost<ThrowOnError extends boolean = false>(
    options: Options<CreateFileManagerEntryV1FileManagerCreatePostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      CreateFileManagerEntryV1FileManagerCreatePostResponse,
      CreateFileManagerEntryV1FileManagerCreatePostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/file/manager/create'
    })
  }

  /**
   * Delete File Manager Entry
   */
  public static deleteFileManagerEntryV1FileManagerDeleteDelete<
    ThrowOnError extends boolean = false
  >(options: Options<DeleteFileManagerEntryV1FileManagerDeleteDeleteData, ThrowOnError>) {
    return (options?.client ?? client).delete<
      DeleteFileManagerEntryV1FileManagerDeleteDeleteResponse,
      DeleteFileManagerEntryV1FileManagerDeleteDeleteError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/file/manager/delete'
    })
  }
}

export class LogCenterService {
  /**
   * Get Global Log Settings
   */
  public static getGlobalLogSettingsV1LogCenterSettingsGet<ThrowOnError extends boolean = false>(
    options?: Options<unknown, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      GetGlobalLogSettingsV1LogCenterSettingsGetResponse,
      GetGlobalLogSettingsV1LogCenterSettingsGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/log-center/settings'
    })
  }

  /**
   * Put Global Log Settings
   */
  public static putGlobalLogSettingsV1LogCenterSettingsPut<ThrowOnError extends boolean = false>(
    options: Options<PutGlobalLogSettingsV1LogCenterSettingsPutData, ThrowOnError>
  ) {
    return (options?.client ?? client).put<
      PutGlobalLogSettingsV1LogCenterSettingsPutResponse,
      PutGlobalLogSettingsV1LogCenterSettingsPutError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/log-center/settings'
    })
  }

  /**
   * Get Global Log Catalog
   */
  public static getGlobalLogCatalogV1LogCenterCatalogGet<ThrowOnError extends boolean = false>(
    options: Options<GetGlobalLogCatalogV1LogCenterCatalogGetData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      GetGlobalLogCatalogV1LogCenterCatalogGetResponse,
      GetGlobalLogCatalogV1LogCenterCatalogGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/log-center/catalog'
    })
  }

  /**
   * Get Global Log Entries
   */
  public static getGlobalLogEntriesV1LogCenterEntriesGet<ThrowOnError extends boolean = false>(
    options: Options<GetGlobalLogEntriesV1LogCenterEntriesGetData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      GetGlobalLogEntriesV1LogCenterEntriesGetResponse,
      GetGlobalLogEntriesV1LogCenterEntriesGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/log-center/entries'
    })
  }

  /**
   * Post Global Log Event
   */
  public static postGlobalLogEventV1LogCenterEventPost<ThrowOnError extends boolean = false>(
    options: Options<PostGlobalLogEventV1LogCenterEventPostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      PostGlobalLogEventV1LogCenterEventPostResponse,
      PostGlobalLogEventV1LogCenterEventPostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/log-center/event'
    })
  }
}

export class StoreService {
  /**
   *  Install Nonebot Module
   * - 安装模块至 NoneBot 实例
   */
  public static installNonebotModuleV1StoreNonebotInstallPost<ThrowOnError extends boolean = false>(
    options: Options<InstallNonebotModuleV1StoreNonebotInstallPostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      InstallNonebotModuleV1StoreNonebotInstallPostResponse,
      InstallNonebotModuleV1StoreNonebotInstallPostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/store/nonebot/install'
    })
  }

  /**
   *  Uninstall Nonebot Module
   * - 卸载 NoneBot 实例中的模块
   */
  public static uninstallNonebotModuleV1StoreNonebotUninstallPost<
    ThrowOnError extends boolean = false
  >(options: Options<UninstallNonebotModuleV1StoreNonebotUninstallPostData, ThrowOnError>) {
    return (options?.client ?? client).post<
      UninstallNonebotModuleV1StoreNonebotUninstallPostResponse,
      UninstallNonebotModuleV1StoreNonebotUninstallPostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/store/nonebot/uninstall'
    })
  }

  /**
   *  Update Nonebot Plugin
   * - 更新 NoneBot 实例中的插件，并将过程写入实例终端日志
   */
  public static updateNonebotPluginV1StoreNonebotUpdatePluginPost<
    ThrowOnError extends boolean = false
  >(options: Options<UpdateNonebotPluginV1StoreNonebotUpdatePluginPostData, ThrowOnError>) {
    return (options?.client ?? client).post<
      UpdateNonebotPluginV1StoreNonebotUpdatePluginPostResponse,
      UpdateNonebotPluginV1StoreNonebotUpdatePluginPostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/store/nonebot/update-plugin'
    })
  }

  /**
   *  Get Nonebot Store Items
   * - 获取 NoneBot Store 中的模块列表
   */
  public static getNonebotStoreItemsV1StoreNonebotListGet<ThrowOnError extends boolean = false>(
    options: Options<GetNonebotStoreItemsV1StoreNonebotListGetData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      GetNonebotStoreItemsV1StoreNonebotListGetResponse,
      GetNonebotStoreItemsV1StoreNonebotListGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/store/nonebot/list'
    })
  }

  /**
   * Search Nonebot Store Item
   * - 搜索 NoneBot Store 中的模块
   */
  public static searchNonebotStoreItemV1StoreNonebotSearchPost<
    ThrowOnError extends boolean = false
  >(options: Options<SearchNonebotStoreItemV1StoreNonebotSearchPostData, ThrowOnError>) {
    return (options?.client ?? client).post<
      SearchNonebotStoreItemV1StoreNonebotSearchPostResponse,
      SearchNonebotStoreItemV1StoreNonebotSearchPostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/store/nonebot/search'
    })
  }
}

export class ProcessService {
  /**
   * Run Process
   * - 运行 NoneBot 实例
   */
  public static runProcessV1ProcessRunPost<ThrowOnError extends boolean = false>(
    options: Options<RunProcessV1ProcessRunPostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      RunProcessV1ProcessRunPostResponse,
      RunProcessV1ProcessRunPostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/process/run'
    })
  }

  /**
   *  Stop Process
   * - 向 NoneBot 实例发送中断信号，优先执行优雅退出
   */
  public static stopProcessV1ProcessStopPost<ThrowOnError extends boolean = false>(
    options: Options<StopProcessV1ProcessStopPostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      StopProcessV1ProcessStopPostResponse,
      StopProcessV1ProcessStopPostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/process/stop'
    })
  }

  /**
   * Write To Process
   * - 向当前实例活动终端写入数据
   */
  public static writeToProcessV1ProcessWritePost<ThrowOnError extends boolean = false>(
    options: Options<WriteToProcessV1ProcessWritePostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      WriteToProcessV1ProcessWritePostResponse,
      WriteToProcessV1ProcessWritePostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/process/write'
    })
  }

  /**
   * Interrupt Process
   * - 向当前实例活动终端发送中断信号
   */
  public static interruptProcessV1ProcessInterruptPost<ThrowOnError extends boolean = false>(
    options: Options<InterruptProcessV1ProcessInterruptPostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      InterruptProcessV1ProcessInterruptPostResponse,
      InterruptProcessV1ProcessInterruptPostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/process/interrupt'
    })
  }

  /**
   * Open Terminal
   * - 为实例创建常驻 Shell 终端会话，可与运行中的机器人并存
   */
  public static openTerminalV1ProcessTerminalOpenPost<ThrowOnError extends boolean = false>(
    options: Options<OpenTerminalV1ProcessTerminalOpenPostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      OpenTerminalV1ProcessTerminalOpenPostResponse,
      OpenTerminalV1ProcessTerminalOpenPostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/process/terminal/open'
    })
  }

  /**
   * Get Terminal Sessions
   * - 获取实例维护终端会话列表
   */
  public static getTerminalSessionsV1ProcessTerminalSessionsGet<
    ThrowOnError extends boolean = false
  >(options: Options<GetTerminalSessionsV1ProcessTerminalSessionsGetData, ThrowOnError>) {
    return (options?.client ?? client).get<
      GetTerminalSessionsV1ProcessTerminalSessionsGetResponse,
      GetTerminalSessionsV1ProcessTerminalSessionsGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/process/terminal/sessions'
    })
  }

  /**
   * Create Terminal Session
   * - 创建新的维护终端会话
   */
  public static createTerminalSessionV1ProcessTerminalSessionCreatePost<
    ThrowOnError extends boolean = false
  >(options: Options<CreateTerminalSessionV1ProcessTerminalSessionCreatePostData, ThrowOnError>) {
    return (options?.client ?? client).post<
      CreateTerminalSessionV1ProcessTerminalSessionCreatePostResponse,
      CreateTerminalSessionV1ProcessTerminalSessionCreatePostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/process/terminal/session/create'
    })
  }

  /**
   * Switch Terminal Session
   * - 切换当前维护终端活动会话
   */
  public static switchTerminalSessionV1ProcessTerminalSessionSwitchPost<
    ThrowOnError extends boolean = false
  >(options: Options<SwitchTerminalSessionV1ProcessTerminalSessionSwitchPostData, ThrowOnError>) {
    return (options?.client ?? client).post<
      SwitchTerminalSessionV1ProcessTerminalSessionSwitchPostResponse,
      SwitchTerminalSessionV1ProcessTerminalSessionSwitchPostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/process/terminal/session/switch'
    })
  }

  /**
   * Delete Terminal Session
   * - 关闭指定维护终端会话
   */
  public static deleteTerminalSessionV1ProcessTerminalSessionDeleteDelete<
    ThrowOnError extends boolean = false
  >(options: Options<DeleteTerminalSessionV1ProcessTerminalSessionDeleteDeleteData, ThrowOnError>) {
    return (options?.client ?? client).delete<
      DeleteTerminalSessionV1ProcessTerminalSessionDeleteDeleteResponse,
      DeleteTerminalSessionV1ProcessTerminalSessionDeleteDeleteError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/process/terminal/session/delete'
    })
  }

  /**
   * Get Terminal Log Key
   * - 获取实例维护 Shell 对应的日志 key
   */
  public static getTerminalLogKeyV1ProcessTerminalLogKeyGet<ThrowOnError extends boolean = false>(
    options: Options<GetTerminalLogKeyV1ProcessTerminalLogKeyGetData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      GetTerminalLogKeyV1ProcessTerminalLogKeyGetResponse,
      GetTerminalLogKeyV1ProcessTerminalLogKeyGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/process/terminal/log-key'
    })
  }

  /**
   * Resize Terminal
   * - 调整实例维护终端的窗口尺寸
   */
  public static resizeTerminalV1ProcessTerminalResizePost<ThrowOnError extends boolean = false>(
    options: Options<ResizeTerminalV1ProcessTerminalResizePostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      ResizeTerminalV1ProcessTerminalResizePostResponse,
      ResizeTerminalV1ProcessTerminalResizePostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/process/terminal/resize'
    })
  }

  /**
   * Get Runtime Log Key
   * - 获取实例运行日志对应的日志 key
   */
  public static getRuntimeLogKeyV1ProcessRuntimeLogKeyGet<ThrowOnError extends boolean = false>(
    options: Options<GetRuntimeLogKeyV1ProcessRuntimeLogKeyGetData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      GetRuntimeLogKeyV1ProcessRuntimeLogKeyGetResponse,
      GetRuntimeLogKeyV1ProcessRuntimeLogKeyGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/process/runtime/log-key'
    })
  }

  /**
   * Execute Command
   * - 在实例目录中的独立 Shell 中执行一次命令，适用于手动安装依赖或排障
   */
  public static executeCommandV1ProcessExecutePost<ThrowOnError extends boolean = false>(
    options: Options<ExecuteCommandV1ProcessExecutePostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      ExecuteCommandV1ProcessExecutePostResponse,
      ExecuteCommandV1ProcessExecutePostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/process/execute'
    })
  }

  /**
   * Get Log History
   * - 获取历史进程日志
   */
  public static getLogHistoryV1ProcessLogHistoryGet<ThrowOnError extends boolean = false>(
    options: Options<GetLogHistoryV1ProcessLogHistoryGetData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      GetLogHistoryV1ProcessLogHistoryGetResponse,
      GetLogHistoryV1ProcessLogHistoryGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/process/log/history'
    })
  }
}

export class ProjectService {
  /**
   *  Get Project Env List
   * - 鑾峰彇 NoneBot 瀹炰緥涓殑鐜鏂囦欢鍒楄〃
   */
  public static getProjectEnvListV1ProjectConfigEnvListGet<ThrowOnError extends boolean = false>(
    options: Options<GetProjectEnvListV1ProjectConfigEnvListGetData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      GetProjectEnvListV1ProjectConfigEnvListGetResponse,
      GetProjectEnvListV1ProjectConfigEnvListGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/config/env/list'
    })
  }

  /**
   *  Create Project Env
   * - 鍒涘缓 NoneBot 瀹炰緥涓殑鐜鏂囦欢
   */
  public static createProjectEnvV1ProjectConfigEnvCreatePost<ThrowOnError extends boolean = false>(
    options: Options<CreateProjectEnvV1ProjectConfigEnvCreatePostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      CreateProjectEnvV1ProjectConfigEnvCreatePostResponse,
      CreateProjectEnvV1ProjectConfigEnvCreatePostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/config/env/create'
    })
  }

  /**
   *  Delete Project Env
   * - 鍒犻櫎 NoneBot 瀹炰緥涓殑鐜鏂囦欢
   */
  public static deleteProjectEnvV1ProjectConfigEnvDeleteDelete<
    ThrowOnError extends boolean = false
  >(options: Options<DeleteProjectEnvV1ProjectConfigEnvDeleteDeleteData, ThrowOnError>) {
    return (options?.client ?? client).delete<
      DeleteProjectEnvV1ProjectConfigEnvDeleteDeleteResponse,
      DeleteProjectEnvV1ProjectConfigEnvDeleteDeleteError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/config/env/delete'
    })
  }

  /**
   *  Use Project Env
   * - 鍒囨崲 NoneBot 瀹炰緥鎵€搴旂敤鐨勭幆澧冩枃浠?
   */
  public static useProjectEnvV1ProjectConfigEnvUsePost<ThrowOnError extends boolean = false>(
    options: Options<UseProjectEnvV1ProjectConfigEnvUsePostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      UseProjectEnvV1ProjectConfigEnvUsePostResponse,
      UseProjectEnvV1ProjectConfigEnvUsePostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/config/env/use'
    })
  }

  /**
   *  Get Project Meta Config
   * - 鑾峰彇 NoneBot 瀹炰緥鍦?.toml 涓殑閰嶇疆淇℃伅
   */
  public static getProjectMetaConfigV1ProjectConfigMetaDetailGet<
    ThrowOnError extends boolean = false
  >(options: Options<GetProjectMetaConfigV1ProjectConfigMetaDetailGetData, ThrowOnError>) {
    return (options?.client ?? client).get<
      GetProjectMetaConfigV1ProjectConfigMetaDetailGetResponse,
      GetProjectMetaConfigV1ProjectConfigMetaDetailGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/config/meta/detail'
    })
  }

  /**
   *  Get Project Nonebot Config
   * - 鑾峰彇 NoneBot 瀹炰緥閰嶇疆淇℃伅
   */
  public static getProjectNonebotConfigV1ProjectConfigNonebotDetailGet<
    ThrowOnError extends boolean = false
  >(options: Options<GetProjectNonebotConfigV1ProjectConfigNonebotDetailGetData, ThrowOnError>) {
    return (options?.client ?? client).get<
      GetProjectNonebotConfigV1ProjectConfigNonebotDetailGetResponse,
      GetProjectNonebotConfigV1ProjectConfigNonebotDetailGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/config/nonebot/detail'
    })
  }

  /**
   *  Get Project Nonebot Plugin Config
   * - 鑾峰彇 NoneBot 瀹炰緥涓墍鏈?NoneBot 鎻掍欢璁剧疆淇℃伅
   */
  public static getProjectNonebotPluginConfigV1ProjectConfigNonebotPluginDetailGet<
    ThrowOnError extends boolean = false
  >(
    options: Options<
      GetProjectNonebotPluginConfigV1ProjectConfigNonebotPluginDetailGetData,
      ThrowOnError
    >
  ) {
    return (options?.client ?? client).get<
      GetProjectNonebotPluginConfigV1ProjectConfigNonebotPluginDetailGetResponse,
      GetProjectNonebotPluginConfigV1ProjectConfigNonebotPluginDetailGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/config/nonebot/plugin/detail'
    })
  }

  /**
   *  Update Project Config
   * - 鏍规嵁妯″潡绫诲瀷鍙婄幆澧冩洿鏂伴厤缃俊鎭?
   * - 璇存槑:
   * * `module_type` 浠呬綔 WebUI 鏇存柊鑷韩瀛樺偍鐨勫疄渚嬩俊鎭紝涓嶄細褰卞搷瀹炰緥鏈綋
   */
  public static updateProjectConfigV1ProjectConfigUpdatePost<ThrowOnError extends boolean = false>(
    options: Options<UpdateProjectConfigV1ProjectConfigUpdatePostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      UpdateProjectConfigV1ProjectConfigUpdatePostResponse,
      UpdateProjectConfigV1ProjectConfigUpdatePostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/config/update'
    })
  }

  /**
   * Get Dotenv File
   * - 鑾峰彇鐜鏂囦欢鍐呭
   */
  public static getDotenvFileV1ProjectConfigDotenvGet<ThrowOnError extends boolean = false>(
    options: Options<GetDotenvFileV1ProjectConfigDotenvGetData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      GetDotenvFileV1ProjectConfigDotenvGetResponse,
      GetDotenvFileV1ProjectConfigDotenvGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/config/dotenv'
    })
  }

  /**
   * Update Dotenv File
   * - 鏇存柊鐜鏂囦欢鍐呭
   */
  public static updateDotenvFileV1ProjectConfigDotenvPut<ThrowOnError extends boolean = false>(
    options: Options<UpdateDotenvFileV1ProjectConfigDotenvPutData, ThrowOnError>
  ) {
    return (options?.client ?? client).put<
      UpdateDotenvFileV1ProjectConfigDotenvPutResponse,
      UpdateDotenvFileV1ProjectConfigDotenvPutError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/config/dotenv'
    })
  }

  /**
   * Get Pyproject File
   */
  public static getPyprojectFileV1ProjectConfigPyprojectGet<ThrowOnError extends boolean = false>(
    options: Options<GetPyprojectFileV1ProjectConfigPyprojectGetData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      GetPyprojectFileV1ProjectConfigPyprojectGetResponse,
      GetPyprojectFileV1ProjectConfigPyprojectGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/config/pyproject'
    })
  }

  /**
   * Update Pyproject File
   */
  public static updatePyprojectFileV1ProjectConfigPyprojectPut<
    ThrowOnError extends boolean = false
  >(options: Options<UpdatePyprojectFileV1ProjectConfigPyprojectPutData, ThrowOnError>) {
    return (options?.client ?? client).put<
      UpdatePyprojectFileV1ProjectConfigPyprojectPutResponse,
      UpdatePyprojectFileV1ProjectConfigPyprojectPutError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/config/pyproject'
    })
  }

  /**
   * Create Project
   * - 创建 NoneBot 实例
   * - 返回对应的日志密钥, 用于日志展现
   */
  public static createProjectV1ProjectCreatePost<ThrowOnError extends boolean = false>(
    options: Options<CreateProjectV1ProjectCreatePostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      CreateProjectV1ProjectCreatePostResponse,
      CreateProjectV1ProjectCreatePostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/create'
    })
  }

  /**
   * Add Project
   * - 添加 NoneBot 实例
   * - 返回对应的日志密钥, 用于日志展现
   */
  public static addProjectV1ProjectAddPost<ThrowOnError extends boolean = false>(
    options: Options<AddProjectV1ProjectAddPostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      AddProjectV1ProjectAddPostResponse,
      AddProjectV1ProjectAddPostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/add'
    })
  }

  /**
   * Get Project Profile
   * - 获取 NoneBot 实例的配置信息
   */
  public static getProjectProfileV1ProjectProfileGet<ThrowOnError extends boolean = false>(
    options: Options<GetProjectProfileV1ProjectProfileGetData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      GetProjectProfileV1ProjectProfileGetResponse,
      GetProjectProfileV1ProjectProfileGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/profile'
    })
  }

  /**
   * Delete Project
   * - 删除 NoneBot 实例
   */
  public static deleteProjectV1ProjectDeleteDelete<ThrowOnError extends boolean = false>(
    options: Options<DeleteProjectV1ProjectDeleteDeleteData, ThrowOnError>
  ) {
    return (options?.client ?? client).delete<
      DeleteProjectV1ProjectDeleteDeleteResponse,
      DeleteProjectV1ProjectDeleteDeleteError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/delete'
    })
  }

  /**
   * List Project
   * - 获取所有 NoneBot 实例基本信息
   */
  public static listProjectV1ProjectListGet<ThrowOnError extends boolean = false>(
    options?: Options<unknown, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      ListProjectV1ProjectListGetResponse,
      ListProjectV1ProjectListGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/list'
    })
  }

  /**
   * Check Project Toml
   * - 检查 NoneBot 实例的 toml 文件并从中获取所需信息
   */
  public static checkProjectTomlV1ProjectCheckTomlPost<ThrowOnError extends boolean = false>(
    options: Options<CheckProjectTomlV1ProjectCheckTomlPostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      CheckProjectTomlV1ProjectCheckTomlPostResponse,
      CheckProjectTomlV1ProjectCheckTomlPostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/check_toml'
    })
  }

  /**
   * Get Plugins
   * - 获取实例的插件列表
   */
  public static getPluginsV1ProjectPluginsGet<ThrowOnError extends boolean = false>(
    options: Options<GetPluginsV1ProjectPluginsGetData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      GetPluginsV1ProjectPluginsGetResponse,
      GetPluginsV1ProjectPluginsGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/plugins'
    })
  }

  /**
   * Get Adapters
   * - 获取实例的适配器列表
   */
  public static getAdaptersV1ProjectAdaptersGet<ThrowOnError extends boolean = false>(
    options: Options<GetAdaptersV1ProjectAdaptersGetData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      GetAdaptersV1ProjectAdaptersGetResponse,
      GetAdaptersV1ProjectAdaptersGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/adapters'
    })
  }

  /**
   * Get Drivers
   * - 获取实例的驱动器列表
   */
  public static getDriversV1ProjectDriversGet<ThrowOnError extends boolean = false>(
    options: Options<GetDriversV1ProjectDriversGetData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      GetDriversV1ProjectDriversGetResponse,
      GetDriversV1ProjectDriversGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/drivers'
    })
  }

  /**
   * Update Project Auto Start
   * - 更新单个 NoneBot 实例的开机自启状态
   */
  public static updateProjectAutoStartV1ProjectAutoStartUsePost<
    ThrowOnError extends boolean = false
  >(options: Options<UpdateProjectAutoStartV1ProjectAutoStartUsePostData, ThrowOnError>) {
    return (options?.client ?? client).post<
      UpdateProjectAutoStartV1ProjectAutoStartUsePostResponse,
      UpdateProjectAutoStartV1ProjectAutoStartUsePostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/auto-start/use'
    })
  }

  /**
   * Update Project Dir
   * - 更新 NoneBot 实例的路径
   */
  public static updateProjectDirV1ProjectUpdateDirPost<ThrowOnError extends boolean = false>(
    options: Options<UpdateProjectDirV1ProjectUpdateDirPostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      UpdateProjectDirV1ProjectUpdateDirPostResponse,
      UpdateProjectDirV1ProjectUpdateDirPostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/project/update-dir'
    })
  }
}

export class SystemService {
  /**
   * Get Security Settings
   */
  public static getSecuritySettingsV1SystemSecurityGet<ThrowOnError extends boolean = false>(
    options?: Options<unknown, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      GetSecuritySettingsV1SystemSecurityGetResponse,
      GetSecuritySettingsV1SystemSecurityGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/system/security'
    })
  }

  /**
   * Update Security Settings
   */
  public static updateSecuritySettingsV1SystemSecurityPut<ThrowOnError extends boolean = false>(
    options: Options<UpdateSecuritySettingsV1SystemSecurityPutData, ThrowOnError>
  ) {
    return (options?.client ?? client).put<
      UpdateSecuritySettingsV1SystemSecurityPutResponse,
      UpdateSecuritySettingsV1SystemSecurityPutError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/system/security'
    })
  }

  /**
   * Get Container Runtime Settings
   */
  public static getContainerRuntimeSettingsV1SystemContainerRuntimeGet<
    ThrowOnError extends boolean = false
  >(options?: Options<unknown, ThrowOnError>) {
    return (options?.client ?? client).get<
      GetContainerRuntimeSettingsV1SystemContainerRuntimeGetResponse,
      GetContainerRuntimeSettingsV1SystemContainerRuntimeGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/system/container/runtime'
    })
  }

  /**
   * Update Container Runtime Settings
   */
  public static updateContainerRuntimeSettingsV1SystemContainerRuntimePut<
    ThrowOnError extends boolean = false
  >(options: Options<UpdateContainerRuntimeSettingsV1SystemContainerRuntimePutData, ThrowOnError>) {
    return (options?.client ?? client).put<
      UpdateContainerRuntimeSettingsV1SystemContainerRuntimePutResponse,
      UpdateContainerRuntimeSettingsV1SystemContainerRuntimePutError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/system/container/runtime'
    })
  }

  /**
   * Test Runtime Settings Connectivity
   */
  public static testRuntimeSettingsConnectivityV1SystemContainerRuntimeTestPost<
    ThrowOnError extends boolean = false
  >(
    options: Options<
      TestRuntimeSettingsConnectivityV1SystemContainerRuntimeTestPostData,
      ThrowOnError
    >
  ) {
    return (options?.client ?? client).post<
      TestRuntimeSettingsConnectivityV1SystemContainerRuntimeTestPostResponse,
      TestRuntimeSettingsConnectivityV1SystemContainerRuntimeTestPostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/system/container/runtime/test'
    })
  }

  /**
   * Benchmark Runtime Presets
   */
  public static benchmarkRuntimePresetsV1SystemContainerRuntimePresetBenchmarkPost<
    ThrowOnError extends boolean = false
  >(
    options: Options<
      BenchmarkRuntimePresetsV1SystemContainerRuntimePresetBenchmarkPostData,
      ThrowOnError
    >
  ) {
    return (options?.client ?? client).post<
      BenchmarkRuntimePresetsV1SystemContainerRuntimePresetBenchmarkPostResponse,
      BenchmarkRuntimePresetsV1SystemContainerRuntimePresetBenchmarkPostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/system/container/runtime/preset/benchmark'
    })
  }

  /**
   * List Runtime Profiles
   */
  public static listRuntimeProfilesV1SystemContainerRuntimeProfileListGet<
    ThrowOnError extends boolean = false
  >(options?: Options<unknown, ThrowOnError>) {
    return (options?.client ?? client).get<
      ListRuntimeProfilesV1SystemContainerRuntimeProfileListGetResponse,
      ListRuntimeProfilesV1SystemContainerRuntimeProfileListGetError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/system/container/runtime/profile/list'
    })
  }

  /**
   * Save Runtime Profile
   */
  public static saveRuntimeProfileV1SystemContainerRuntimeProfileSavePost<
    ThrowOnError extends boolean = false
  >(options: Options<SaveRuntimeProfileV1SystemContainerRuntimeProfileSavePostData, ThrowOnError>) {
    return (options?.client ?? client).post<
      SaveRuntimeProfileV1SystemContainerRuntimeProfileSavePostResponse,
      SaveRuntimeProfileV1SystemContainerRuntimeProfileSavePostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/system/container/runtime/profile/save'
    })
  }

  /**
   * Apply Runtime Profile
   */
  public static applyRuntimeProfileV1SystemContainerRuntimeProfileApplyPost<
    ThrowOnError extends boolean = false
  >(
    options: Options<ApplyRuntimeProfileV1SystemContainerRuntimeProfileApplyPostData, ThrowOnError>
  ) {
    return (options?.client ?? client).post<
      ApplyRuntimeProfileV1SystemContainerRuntimeProfileApplyPostResponse,
      ApplyRuntimeProfileV1SystemContainerRuntimeProfileApplyPostError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/system/container/runtime/profile/apply'
    })
  }

  /**
   * Delete Runtime Profile
   */
  public static deleteRuntimeProfileV1SystemContainerRuntimeProfileDeleteDelete<
    ThrowOnError extends boolean = false
  >(
    options?: Options<
      DeleteRuntimeProfileV1SystemContainerRuntimeProfileDeleteDeleteData,
      ThrowOnError
    >
  ) {
    return (options?.client ?? client).delete<
      DeleteRuntimeProfileV1SystemContainerRuntimeProfileDeleteDeleteResponse,
      DeleteRuntimeProfileV1SystemContainerRuntimeProfileDeleteDeleteError,
      ThrowOnError
    >({
      ...options,
      url: '/v1/system/container/runtime/profile/delete'
    })
  }
}
