name: Release

on:
  push:
    tags:
      - v*

jobs:
  check-version:
    name: Check Version
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      VERSION: ${{ steps.version.outputs.VERSION }}
      TAG_VERSION: ${{ steps.version.outputs.TAG_VERSION }}
      TAG_NAME: ${{ steps.version.outputs.TAG_NAME }}
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4

      - name: 🚀 Setup Python environment
        uses: ./.github/actions/setup-python

      - name: 🔖 Get version
        id: version
        run: |
          echo "VERSION=$(poetry version -s)" >> $GITHUB_OUTPUT
          echo "TAG_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: ✅ Check version
        if: steps.version.outputs.VERSION != steps.version.outputs.TAG_VERSION
        run: exit 1

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: check-version
    permissions:
      id-token: write
      contents: write
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4

      - name: 🚀 Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: 🚀 Setup node
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"

      - name: 🔧 Install dependencies
        run: pnpm install

      - name: 🚧 Build dist files
        run: pnpm build

      - name: 📦️ Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: nb_cli_plugin_webui/dist

      - name: 🚀 Setup Python environment
        uses: ./.github/actions/setup-python

      - name: 🚧 Build package
        run: |
          poetry run compile
          poetry build

      - name: 🚀 Create or Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.check-version.outputs.TAG_NAME }}
          name: ${{ needs.check-version.outputs.TAG_NAME }}
          files: |
            dist/*.tar.gz
            dist/*.whl
          generate_release_notes: true
